eureka:
  instance:
    hostname: localhost
  client:         # Eureka Client config
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8060

spring:
  application:
    name: CartItem-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CartItem_ServiceDB   # Database Config
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect