server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: Config-Server

  cloud:
    config:
      server:       # Configuration for Config server and Path where the configs for the Services are
        native:
          search-locations: classpath:/configurations

